## Problem 1

In [7]:
import numpy as np
arr = np.random.randint(1,50,size = (5,4))
print(f"The array formed is {arr}")
an_diag = np.fliplr(arr).diagonal()
print(f"The anti diagonal of the numpy array is {an_diag}")


The array formed is [[ 6 35 15 21]
 [46 41 26 37]
 [43  7 31 32]
 [35 48 13 40]
 [26 31 42 35]]
The anti diagonal of the numpy array is [21 26  7 35]


In [10]:
max_row = arr.max(axis = 1)
print(f"The maximum value in each column is {max_row}")

The maximum value in each column is [35 46 43 48 42]


In [13]:
mean = np.mean(arr)
new_arr = arr[arr<= mean]
print(new_arr)

[ 6 15 21 26  7 13 26]


In [16]:
def numpy_boundary_traversal(matrix):
  top = matrix[0,:]
  right = matrix[1:-1,-1]
  bottom = matrix[-1,::-1]
  left = matrix[-2:0:-1,0]
  return np.concatenate((top, right, bottom, left))

print(numpy_boundary_traversal(arr))

[ 6 35 15 21 37 32 40 35 42 31 26 35 43 46]


## Problem 2

In [18]:
a = np.random.rand(20)*10
print(a)

[4.42862993 9.14116625 1.90487948 4.18148104 1.92134265 6.19392672
 5.8987718  7.05448313 8.33130936 0.54392116 6.91758939 0.12034667
 5.65016314 0.98118583 6.59175098 9.08086117 5.22850758 6.96845437
 8.61033549 7.67855788]


In [19]:
a = a.round(2)
print(a)

[4.43 9.14 1.9  4.18 1.92 6.19 5.9  7.05 8.33 0.54 6.92 0.12 5.65 0.98
 6.59 9.08 5.23 6.97 8.61 7.68]


In [21]:
min = a.min()
max = a.max()
med = np.median(a)
print(f"The minimum value is {min}")
print(f"The maximum value is {max}")
print(f"The median value is {med}")


The minimum value is 0.12
The maximum value is 9.14
The median value is 6.045


In [22]:
a = np.where( a< 5, a**2, a)
print(a)

[1.96249e+01 9.14000e+00 3.61000e+00 1.74724e+01 3.68640e+00 6.19000e+00
 5.90000e+00 7.05000e+00 8.33000e+00 2.91600e-01 6.92000e+00 1.44000e-02
 5.65000e+00 9.60400e-01 6.59000e+00 9.08000e+00 5.23000e+00 6.97000e+00
 8.61000e+00 7.68000e+00]


In [23]:
def numpy_alternate_sort(arr):
  sort_arr = np.sort(arr)
  result = []
  i, j =0, len(sort_arr)-1
  while i<=j:
    if i== j:
      result.append(sort_arr[i])
    else:
      result.append(sort_arr[i])
      result.append(sort_arr[j])
    i+=1
    j-=1
  return np.array(result)

print(numpy_alternate_sort(a))

[1.44000e-02 1.96249e+01 2.91600e-01 1.74724e+01 9.60400e-01 9.14000e+00
 3.61000e+00 9.08000e+00 3.68640e+00 8.61000e+00 5.23000e+00 8.33000e+00
 5.65000e+00 7.68000e+00 5.90000e+00 7.05000e+00 6.19000e+00 6.97000e+00
 6.59000e+00 6.92000e+00]


## Problem 3

In [34]:
import pandas as pd
names = [f"Student{i+1}" for i in range(10)]
Subjects = np.random.choice(["Calculus", "Thermodynamics", "Fluid"],10)
Scores = np.random.randint(50,100, size = 10)
df = pd.DataFrame({"Name": names,"Subject":Subjects, "Score": Scores})
print(df)

        Name         Subject  Score
0   Student1           Fluid     65
1   Student2           Fluid     67
2   Student3  Thermodynamics     53
3   Student4        Calculus     60
4   Student5  Thermodynamics     75
5   Student6           Fluid     97
6   Student7  Thermodynamics     86
7   Student8        Calculus     76
8   Student9           Fluid     88
9  Student10           Fluid     67


In [35]:
df['Grade'] = df['Score'].apply(lambda x: 'A' if x>90 else ('B' if x>80 else ('C' if x>70 else( 'D' if x>60 else 'F'))))
print(df)

        Name         Subject  Score Grade
0   Student1           Fluid     65     D
1   Student2           Fluid     67     D
2   Student3  Thermodynamics     53     F
3   Student4        Calculus     60     F
4   Student5  Thermodynamics     75     C
5   Student6           Fluid     97     A
6   Student7  Thermodynamics     86     B
7   Student8        Calculus     76     C
8   Student9           Fluid     88     B
9  Student10           Fluid     67     D


In [36]:
df = df.sort_values(by = 'Score', ascending = False)
print(df)


        Name         Subject  Score Grade
5   Student6           Fluid     97     A
8   Student9           Fluid     88     B
6   Student7  Thermodynamics     86     B
7   Student8        Calculus     76     C
4   Student5  Thermodynamics     75     C
1   Student2           Fluid     67     D
9  Student10           Fluid     67     D
0   Student1           Fluid     65     D
3   Student4        Calculus     60     F
2   Student3  Thermodynamics     53     F


In [40]:
sub = np.unique(df['Subject'])
for s in sub:
  mean = df[df['Subject']==s]['Score'].mean()
  print(f"The mean score for {s} is {mean}")

The mean score for Calculus is 68.0
The mean score for Fluid is 76.8
The mean score for Thermodynamics is 71.33333333333333


In [41]:
def pandas_filter_dataframe(df):
  return df[df['Score']>80]
filtered_df = pandas_filter_dataframe(df)
print(filtered_df)


       Name         Subject  Score Grade
5  Student6           Fluid     97     A
8  Student9           Fluid     88     B
6  Student7  Thermodynamics     86     B


## Problem 4

In [9]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import random

positive_reviews = ['Great Movie!', 'Very Good Movie','I loved it!!', 'True Cinema', 'Excellent', 'Enjoyed it!!!','Worth Watching', 'Money well spent', 'A movie of its own', 'Exceptionally great']*5
negative_reviews = ['trash', 'shit!!!!', 'Wasted my money', 'Not recommended', 'Exceptionally bad', 'Terrible Movie', 'I hated it', 'Really bad', ' Awfull experience','Waste of time']*5

reviews = positive_reviews+ negative_reviews
sentiments = ['positive']*50 + ['negative']*50
df= pd.DataFrame({'Review':reviews, 'Sentiment': sentiments})

vectorizer = CountVectorizer(max_features = 500, stop_words='english')
X = vectorizer.fit_transform(df['Review'])
y = df['Sentiment']

x_train, x_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state= 30)
model = MultinomialNB()
model.fit(x_train,y_train)

y_pred = model.predict(x_test)
print(accuracy_score(y_test,y_pred))

def predict_review_sentiment(mode, vectorizer, review):
  review_vector = vectorizer.transform([review])
  return model.predict(review_vector)[0]

print(predict_review_sentiment(model, vectorizer, 'This movie was bad'))

1.0
negative


## Problem 5

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
g = ['good product', ' worth it', 'good features','great functionality','nice color','great usage', 'Usefull','Nice','Important','Great experience']*5
b = ['not worth it','bad design','not functional','bad color','trash', 'skill issue','Not usefull', 'Useless','Unimportant','Very Bad experience']*5
label = ['good']*50+ ['bad']*50
texts= g+b
df = pd.DataFrame({'Text':texts,'Label':label})

tfidf = TfidfVectorizer(max_features = 300, stop_words='english')
x2= tfidf.fit_transform(df['Text'])
y2= df['Label']
x_train,x_test,y_train,y_test = train_test_split(x2,y2,test_size = 0.25,random_state=20)
log = LogisticRegression()
log.fit(x_train,y_train)
y_pred = log.predict(x_test)
print(classification_report(y_test,y_pred))

def text_preprocess_vectorizer(texts, vectorizer):
  return vectorizer.transform(texts)


              precision    recall  f1-score   support

         bad       0.91      0.83      0.87        12
        good       0.86      0.92      0.89        13

    accuracy                           0.88        25
   macro avg       0.88      0.88      0.88        25
weighted avg       0.88      0.88      0.88        25



In [23]:
print(text_preprocess_vectorizer(["Nice and good product"], tfidf).toarray())

[[0.         0.         0.         0.         0.         0.
  0.         0.54134764 0.         0.         0.         0.54134764
  0.64333931 0.         0.         0.         0.         0.
  0.         0.        ]]
